import groovy.util.XmlSlurper
def customers = new XmlSlurper().parse(new File('xml-handling/customers.xml'))
for (customer in customers.corporate.customer) {
    println "${customer.@name} works for ${customer.@company}"
}
